### ISSUE TITLE
Update Resource explorer - look and feel - dont pick

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-app-kit#1849]
### Description
This is a parent story for updating the look and feel for the Resource explorer panel i.e the left panel within the dashboard

### Acceptance Criteria

- [ ] The look and feel of the resource explorer is as shown in the screen
- [ ] Cloudscape component and its design tokens should be used wherever applicable
- [ ] No Change in functionality
- [ ] All the sub tasks are complete

**Additional context**

- Use Readme.md to get some demo data from a AWS account
- live data helps with testing

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-app-kit/issues/1851
- [ ] https://github.com/awslabs/iot-app-kit/issues/1852
- [ ] https://github.com/awslabs/iot-app-kit/issues/1853
- [ ] https://github.com/awslabs/iot-app-kit/issues/1854
- [ ] https://github.com/awslabs/iot-app-kit/issues/1855
- [ ] https://github.com/awslabs/iot-app-kit/issues/1857
- [ ] https://github.com/awslabs/iot-app-kit/issues/1856
```
![Screenshot 2023-09-01 at 2 05 04 PM](https://github.com/awslabs/iot-app-kit/assets/135036199/7d164aaa-52dc-497a-970d-8e318d8c1c81)
