### ISSUE TITLE
Update Table Widget - Dashboard

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-app-kit#1858]
**Additional context**

### Acceptance Criteria

- [x] The user should be able to scroll horizontally
- [x] The user should be able to scroll vertically
- [x] The user should be able to change the column width

PS: all the above is applicable in both edit and view mode

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-app-kit/issues/1859
- [ ] https://github.com/awslabs/iot-app-kit/issues/1872
- [ ] https://github.com/awslabs/iot-app-kit/issues/1871
- [ ] https://github.com/awslabs/iot-app-kit/issues/1873
- [ ] https://github.com/awslabs/iot-app-kit/issues/1870
- [ ] https://github.com/awslabs/iot-app-kit/issues/1889
- [ ] https://github.com/awslabs/iot-app-kit/issues/1890
- [ ] https://github.com/awslabs/iot-app-kit/issues/1891
```

**Comment by nadeswal** [comment]
UX details : Refer the table cloudscape component and follow the design + dev guidelines as much as possible. 
Link: [https://cloudscape.design/components/table/?tabId=playground](url)

**Comment by diehbria** [comment]
issues have been resolved
