### ISSUE TITLE
Chart fit and finish - parent ticket

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1918]
Parent ticket for all tasks related to charts (i.e. line chart, scatter chart)

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-app-kit/issues/1919
- [ ] https://github.com/awslabs/iot-app-kit/issues/1920
- [ ] https://github.com/awslabs/iot-app-kit/issues/1921
- [ ] https://github.com/awslabs/iot-app-kit/issues/1922
- [ ] https://github.com/awslabs/iot-app-kit/issues/1923
- [ ] https://github.com/awslabs/iot-app-kit/issues/1924
- [ ] https://github.com/awslabs/iot-app-kit/issues/1925
- [ ] https://github.com/awslabs/iot-app-kit/issues/1926
- [ ] https://github.com/awslabs/iot-app-kit/issues/1928
- [ ] https://github.com/awslabs/iot-app-kit/issues/1929
- [ ] https://github.com/awslabs/iot-app-kit/issues/1930
- [ ] https://github.com/awslabs/iot-app-kit/issues/1938
- [ ] https://github.com/awslabs/iot-app-kit/issues/1952
- [ ] https://github.com/awslabs/iot-app-kit/issues/1953
- [ ] https://github.com/awslabs/iot-app-kit/issues/2002
- [ ] https://github.com/awslabs/iot-app-kit/issues/2055
```
