### ISSUE TITLE
Chart fit and finish - Delete behavior for charts

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1921]
Behavior:
Single delete will take the chart title not possible now as there is a dependency on config panel title name. For multi-select: rewrite confirmation to “Delete selected widgets.”

When deleting a chart, there are the following changes required:

```[tasklist]
### UX
- [x] Guidance for the UX for the delete friction
```

```[tasklist]
### Tasks
- [ ] Delete key should open of confirmation (see https://cloudscape.design/patterns/resource-management/delete/delete-with-simple-confirmation/)
- [ ] Implement test which utilizes the modal to delete a widget
- [ ] Prevent the users from dragging the chart by dragging the delete "X" icon
- [ ] Fix issue where delete key sometimes does not result in the deletion
```

**Comment by nadeswal** [comment]
<img width="860" alt="Screenshot 2023-09-20 at 11 28 26 AM" src="https://github.com/awslabs/iot-app-kit/assets/141063047/26ebd3c0-6776-461c-89f1-1b9a12f906b0">

Please use the simple confirmation delete modal for this experience.

**Comment by gmuralidharreddy** [comment]
There is a multi-select option and delete all selected widgets at a time, so can we go like the below screenshots?

for single select:
![image](https://github.com/awslabs/iot-app-kit/assets/139960352/8f5226f6-37c7-45b9-80cf-0e01a84a3906)


for multi-select:
![image](https://github.com/awslabs/iot-app-kit/assets/139960352/08287206-678b-40e0-ab39-ff82c4cc77f6)


Note: CSS changes not yet provided.
