### ISSUE TITLE
Chart fit and finish - Threshold config implementation

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1938]
Toggle within the threshold configuration panel currently has no impact. Expect behavior is that when the toggle is on, the data points/lines that meet the criteria of a threhold will be colored correctly.

i.e. if I have a threshold that has the condition "RED if LESS THAN 20", with the "apply threshold color across all data" as true, the line and data points of the data set should be visualized as red for the data where Y is less than 20.

![Screenshot 2023-09-18 at 2 40 34 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/fbab0428-0504-44ce-8c0a-86d52bd6a01d)

Refer to https://github.com/awslabs/iot-app-kit/blob/main/packages/react-components/src/utils/thresholdUtils.ts#L69 on how to determine the thresholds priority

```[tasklist]
### Tasks
- [ ] When multiple conditions are present, the condition with the highest priority is used to determine the correct coloring
- [ ] No coloring of data points / lines occurs when "apply threshold color across all data" is false
- [ ] Color of data points occurs when "apply threshold color across all data" is true
- [ ] Respective unit tests / integration tests are in place
- [ ] Work is accessible according to WCAG 2.1 AA
```

**Comment by mnischay** [comment]
@diehbria : only callout is "the condition with the highest priority is used to determine the correct coloring" --> what is the logic to determine the priority, sorry if its already documented elsewhere

**Comment by hwandersman** [comment]
This will be resolved by PR #1927
