### ISSUE TITLE
Dashboard: viewport incorrectly resets when switching edit/view mode

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1939]
Currently, viewport will alter when changing between view/edit mode.

The desired behavior is that the viewport does not change upon switching between edit and view mode.

```[tasklist]
### Tasks
- [ ] Ensure that viewport is not altered when changing from view to edit mode
- [ ] Ensure that viewport is not altered when changing from edit to view mode
- [ ] Ensure that viewport is not altered upon saving
- [ ] Capture behaviors in automated tests
```

**Comment by diehbria** [comment]
this issue is being tackled and tracked internally by the IoT App Kit team so closing this issue
