### ISSUE TITLE
Dashboard - parent ticket

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1949]
Dashboard related tasks

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-app-kit/issues/1939
- [ ] https://github.com/awslabs/iot-app-kit/issues/1948
- [ ] https://github.com/awslabs/iot-app-kit/issues/1950
- [ ] https://github.com/awslabs/iot-app-kit/issues/1977
- [ ] https://github.com/awslabs/iot-app-kit/issues/1981
- [ ] https://github.com/awslabs/iot-app-kit/issues/1984
- [ ] https://github.com/awslabs/iot-app-kit/issues/1986
- [ ] https://github.com/awslabs/iot-app-kit/issues/2003
- [ ] https://github.com/awslabs/iot-app-kit/issues/2036
- [ ] https://github.com/awslabs/iot-app-kit/issues/2046
```
