### ISSUE TITLE
Resource explorer: table preferences "visible columns" bug

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1980]
This task is to fix a bug where the asset preferences are not working as expected

To recreate the issue, open up the dashboard and click on the gear icon under the browse assets search bar - shown in the img below
<img width="632" alt="Screenshot 2023-09-27 at 7 23 22 AM" src="https://github.com/awslabs/iot-app-kit/assets/77755322/4f6a9fa8-d7fd-467d-9552-ed9af44147d2">

 
Opening this menu will bring the "Asset preferences" modal. Attempt Showing fields (such as "Creation Date".

The expectation is that a column is present with data displayed (if available). The current observed behavior is that the "Select visible content" only works for "Asset name" and "Asset description"
<img width="868" alt="Screenshot 2023-09-27 at 7 23 49 AM" src="https://github.com/awslabs/iot-app-kit/assets/77755322/2cb23b22-7473-46b1-81ea-091189309258">

```[tasklist]
### Tasks
- [ ] visible column settings in asset preferences works for all columns
- [ ] Test is in place to assure no regression
- [ ] Confirm no other bugs within asset preferences. If bugs found, document them in ticket and address (can be part of separate PR)
```
