### ISSUE TITLE
Dashboard: line thickness customization on charts

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1995]
This task enables users of the IoT App Kit dashboard to configure the thickness of a line at a per-property and widget level through the dashboard configuration panel.

## User experience of configuration panel

There are two ways for users to customize the line thickness - at the widget level, or the property level. Widget level settings will automatically apply to all properties, unless a property has overridden the widget level settings by disabling the "Use default style" checkbox.

## Widget level configuration

Widget level configurations for the line widget will be found under the "style tab", under the "Line style" sub-section (may not exist currently). 
![line-1](https://github.com/awslabs/iot-app-kit/assets/77755322/88b34d80-3d2d-4610-b6a7-a1254e12c1ed)

Within the "line style" sub section, a new dropdown will be added labeled "Thickness":
![line-2](https://github.com/awslabs/iot-app-kit/assets/77755322/b40bfc80-43f0-4e2e-9a7e-07721fd95f1a)

From the "thickness" drop down, there will be three choices:
Thin - 1px
Normal - 2px
Thick - 5px

"Normal" thickness will be the default

## Property level configuration

A user will click on a line chart, and on the right-side configuration panel, within the "Properties and alarms" section there will be a "Line Style" section.

From the "thickness" drop down, there will be three choices:
Thin - 1px
Normal - 2px
Thick - 5px

When a user checks "Use default Style", the drop-down will become disabled, and revert back to the default line style as configured at the widget level.

![line-3](https://github.com/awslabs/iot-app-kit/assets/77755322/169ac467-8944-40a1-9c2d-93e3abd20743)

## Line chart component

The line chart will be updated so that the line chart reflects the line thickness specified in the dashboard definition

## Implementation Information
Follow the same pattern as defined in the Implementation Information for - https://github.com/awslabs/iot-app-kit/issues/2029

The line thickness property setting is defined at: `LineScatterChartWidget['properties']['queryConfig']['query']['assets'][number]['properties'][number]['line']['thickness'];`

Line thickness is a number instead of an enum. We will need to map the string value from the dropdown to the pixel value.

Line thickness also is not controllable at the widget level, but If the user toggles the use default styles, we should still set thickness to undefined just as we do line style.

```[tasklist]
### Tasks
- [ ] Create widget level "line thickness" settings for line chart
- [ ] Create property level "line thickness" settings for line chart
- [ ] Ensure settings only appear for the echarts based chart
- [ ] Ensure styling of the "properties and alarms" section matches the above mockup
- [ ] Update line chart to display updated line thickness based on thickness selected
- [ ] "property" settings match included UX mocks (may not match currently)
```
