### ISSUE TITLE
Dashboard: side panels toggle open hit box is inccorect

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2003]
Currently, the "hit box" for toggling icons is set to the SVG icon, rather than the outter circle, resulting in a poor UX where users will try to open, but cannot.

<img width="75" alt="Screenshot 2023-09-28 at 1 51 53 PM (1)" src="https://github.com/awslabs/iot-app-kit/assets/77755322/1a134f73-f190-4f81-97a8-64473827b699">

<img width="423" alt="Screenshot 2023-09-28 at 4 56 09 PM" src="https://github.com/awslabs/iot-app-kit/assets/77755322/65113833-c5f7-43f3-9b4b-a8d5ee5197e0">

```[tasklist]
### Tasks
- [x] Make the entire circle button the "hit target" for the "resource explorer" and "config panel" buttons
- [x] Add a "tool tip" that appears on hover (as shown below)
- [x] config panel tool tip should say "Configuration"
- [x] resource explorer tool tip should say "Resource explorer"
```

**Comment by diehbria** [comment]
verified completed
