### ISSUE TITLE
[Dashboard] Naming inconsistency

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2166]
## Overview
Widgets on the dashboard have a "title" field, where a user can define a string which is rendered in the top left of the widget panel

**Current behavior**: Title only works as expected for the line chart

**Expected behavior**: Title works also works for bar chart, timeline, KPI, status and table widget

```[tasklist]
### Tasks
- [ ] bar chart title works and is editable via configuration panel
- [ ] timeline title works and is editable via configuration panel
- [ ] KPI title works and is editable via configuration panel
- [ ] status title works and is editable via configuration panel
```

**Comment by diehbria** [comment]
closed in favor of https://github.com/awslabs/iot-app-kit/issues/2312. not going to worry about making KPI and status have "titles"
