### ISSUE TITLE
[Widgets] Gauge

### ISSUE THREAD

**Issue by corteggiano** [awslabs/iot-app-kit#2624]
This task is to implement a new gauge widget in react-components utilizing the echarts gauge

Echarts Gauge examples - https://echarts.apache.org/examples/en/index.html#chart-type-gauge
Echarts Gauge series type - https://echarts.apache.org/en/option.html#series-gauge.type

the following designs are not taking echarts into account so if there are some things that cant be done exactly per the designs that's okay!

<img width="664" alt="image" src="https://github.com/awslabs/iot-app-kit/assets/28601414/0ee16365-3dcb-4a31-8572-ad1eb22abd57">
<img width="664" alt="OtherVariations" src="https://github.com/awslabs/iot-app-kit/assets/28601414/c53aca15-985d-41ef-9ee0-4f1c509352d2">

<img width="448" alt="Screenshot 2024-03-01 at 12 23 46 PM" src="https://github.com/awslabs/iot-app-kit/assets/107281089/ebb187e8-564e-4cbb-8220-b295c4af9585">

```[tasklist]
### Tasks
- [ ] https://github.com/awslabs/iot-app-kit/issues/2631
- [ ] https://github.com/awslabs/iot-app-kit/issues/2665
- [ ] https://github.com/awslabs/iot-app-kit/issues/2635
- [ ] https://github.com/awslabs/iot-app-kit/issues/2634
- [ ] https://github.com/awslabs/iot-app-kit/issues/2633
```
